name: Frontend CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export PATH="/home/ubuntu/.nvm/versions/node/v24.21.0/bin:$PATH"

            cd ~/FE

            git pull origin main

            npm ci

            REACT_APP_API_URL="${{ secrets.REACT_APP_API_URL }}" npm run build

            pm2 restart all
